apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-cm
spec:
  serviceName: "nginx-cm"
  replicas: 1
  selector:
    matchLabels:
      app: nginx-cm
  template:
    metadata:
      labels:
        app: nginx-cm
    spec:
      containers:
      - name: nginx-cm
        image: nginx-cm:latest # Replace with your actual image registry
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: S3_ENDPOINT
          value: "https://s3.us-east-1.amazonaws.com" # Optional, defaults to AWS US-East-1
        - name: S3_BUCKET
          value: "your-s3-bucket-name"
        - name: S3_FOLDER
          value: "configs/cluster-1"
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: access-key
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: secret-key
        volumeMounts:
        - name: data
          mountPath: /nginx-cm
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 20Mi

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cm-lb
spec:
  type: LoadBalancer
  selector:
    app: nginx-cm
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
